dist: bionic

env:
  global:
    - PGPORT=5433

addons:
  postgresql: 11
  apt:
    packages:
    - libkakasi2-dev
    - libutf8proc-dev
    - pandoc
    - postgresql-server-dev-11
    - postgresql-plpython3-11
    - python3-pip
    - postgresql-11-postgis-2.5
    - postgresql-11-postgis-2.5-scripts

before_install:
  - sudo pip3 install pythainlp
  - createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template0 gis
  - psql --dbname=gis --command="CREATE EXTENSION fuzzystrmatch"
  - psql --dbname=gis --command="CREATE EXTENSION unaccent"
  - psql --dbname=gis --command="CREATE EXTENSION postgis"
  - psql --dbname=gis --command="CREATE EXTENSION hstore"
  - psql --dbname=gis --command="CREATE EXTENSION plpython3u"

install:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo make install
  - psql --dbname=gis --command="CREATE EXTENSION osml10n"
  - psql --dbname=gis --command="CREATE EXTENSION osml10n_thai_transcript"

script:
  - cd ${TRAVIS_BUILD_DIR}/tests
  - ./runtests.sh gis
