dist: bionic

env:
  global:
    - PGPORT=5433

addons:
  postgresql: 11
  apt:
    packages:
    - libkakasi2-dev
    - libutf8proc-dev
    - pandoc
    - postgresql-server-dev-11
    - postgresql-11-postgis-2.5
    - postgresql-11-postgis-2.5-scripts

before_install:
  - createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template0 l10n
  - psql --command="CREATE EXTENSION fuzzystrmatch"
  - psql --command="CREATE EXTENSION unaccent"
  - psql --command="CREATE EXTENSION postgis"
  - psql --command="CREATE EXTENSION hstore"

install:
  - cd ${TRAVIS_BUILD_DIR}
  - sudo make install
  - psql --command="CREATE EXTENSION osml10n"

script:
  - cd ${TRAVIS_BUILD_DIR}/tests
  - ./runtests.sh l10n
